// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpainChampionship;

#nullable disable

namespace SpainChampionship.Migrations
{
    [DbContext(typeof(SpainChempDB))]
    [Migration("20240706144829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpainChampionship.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Madrid",
                            Draw = 0,
                            Lose = 0,
                            Name = "Real Madrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            City = "Barcelona",
                            Draw = 0,
                            Lose = 0,
                            Name = "Barcelona",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            City = "Madrid",
                            Draw = 0,
                            Lose = 0,
                            Name = "Atletico Madrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            City = "Valencia",
                            Draw = 0,
                            Lose = 0,
                            Name = "Valencia",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            City = "Sevilla",
                            Draw = 0,
                            Lose = 0,
                            Name = "Sevilla",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            City = "San Sebastian",
                            Draw = 0,
                            Lose = 0,
                            Name = "Real Sociedad",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            City = "Villarreal",
                            Draw = 0,
                            Lose = 0,
                            Name = "Villarreal",
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
